import { z } from "zod";

export const UpdateParticularsOfInstallationsReferredToInThisReportSchema =
  z.object({
    id: z.string().cuid(),
    maximumDemand: z.string().optional(),
    distributorsFacility: z.boolean().optional(),
    installationEarthElectrodes: z.boolean().optional(),
    earthElectrodeType: z.string().optional(),
    earthElectrodeLocation: z.string().optional(),
    electrodeResistanceToEarth: z.string().optional(),
    earthingConductorMaterial: z.string().optional(),
    earthingConductorCSA: z.string().optional(),
    earthingConductorVerified: z.boolean().optional(),
    mainProtectiveBondingConductorMaterial: z.string().optional(),
    mainProtectiveBondingConductorCSA: z.string().optional(),
    mainProtectiveBondingConductorVerified: z.boolean().optional(),
    waterInstallationPipes: z.string().optional(),
    gasInstallationPipes: z.string().optional(),
    structuralSteel: z.string().optional(),
    oilInstallationPipes: z.string().optional(),
    lightningProtection: z.string().optional(),
    other: z.string().optional(),
    mainSwitchLocation: z.string().optional(),
    mainSwitchBSNumber: z.string().optional(),
    mainSwitchType: z.string().optional(),
    mainSwitchRating: z.string().optional(),
    mainSwitchPoles: z.string().optional(),
    mainSwitchCurrentRating: z.string().optional(),
    mainSwitchVoltageRating: z.string().optional(),
    mainSwitchRCDOperatingCurrent: z.string().optional(),
    mainSwitchRCDType: z.string().optional(),
    mainSwitchRCDRatedTimeDelay: z.string().optional(),
    mainSwitchRCDMeasuredOperatingTime: z.string().optional(),
  });
