import { z } from "zod";
import { schema } from "./schema";

export const DefaultValues: z.infer<typeof schema> = {
  contractorTradingName: "Acme Electrical Services",
  contractorAddress: "123 High Street, Manchester, M1 1AA",
  contractorPhone: "0161 123 4567",
  contractorEmail: "info@acmeelectrical.co.uk",
  contractorGoverningBody: "National Electrical Association",
  contractorGoverningBodyNumber: "NEA123456",

  clientReferenceNumber: "CL-001234",
  clientTradingName: "XYZ Housing Association",
  clientAddress: "456 Green Lane, Manchester, M2 2BB",
  clientPostcode: "M2 2BB",
  clientTelephone: "0161 234 5678",

  propertyReferenceNumber: "PR-789012",
  propertyOccupier: "John Doe",
  propertyAddress: "789 Oak Road, Manchester, M3 3CC",
  propertyPostcode: "M3 3CC",
  propertyTelephone: "0161 345 6789",

  purpose: "Electrical Installation Condition Report",
  startDate: new Date("2025-02-06T00:00:00"),
  endDate: new Date("2025-02-07T00:00:00"),
  recordsAvailable: true,
  previousReportAvailable: false,
  previousReportDate: new Date("2024-02-06T00:00:00"),

  descriptionOfPremises: "Residential Property",
  estimatedAgeOfElectricalInstallation: "10 years",
  evidenceOfAlterations: false,
  estimatedAgeOfAlterations: "0 years",

  generalConditionOfTheInstallation: "Good",
  overallAssessmentOfTheInstallation: "Satisfactory",

  regulationAccordance: "BS7671",
  electricalInstalationCoveredByThisReport: "Full Installation",
  agreedLimitations: "None",
  agreedLimitationsWith: "John Doe",
  operationalLimitations: "None",

  inspectorsName: "John Doe",
  inspectorsSignature: "",
  inspectorsSignatureDate: new Date(),
  retestDate: new Date("2026-02-06T00:00:00"),
  reasonForRecommendation: "Routine check",
  qualifiedSupervisorsName: "Jane Doe",
  qualifiedSupervisorsSignature: "",
  qualifiedSupervisorsSignatureDate: new Date(),

  systemTypeAndEarthingArrangemets: "TN-S",
  supplyProtectiveDeviceBSNumber: "1234",
  supplyProtectiveDeviceType: "RCD",
  supplyProtectiveDeviceRatedCurrent: "100A",
  numberAndTypeOfLiveConductors: "3 (L1, L2, L3)",
  confirmationOfSupplyPolarity: true,
  otherSourcesOfSupply: "None",
  nominalVoltageBetweenLines: "415V",
  nominalLineVoltageToEarth: "230V",
  nominalFrequency: "50Hz",
  prospectiveFaultCurrent: "10kA",
  externalEarthFaultLoopImpedance: "0.5Ω",

  maximumDemand: "100A",
  distributorsFacility: true,
  installationEarthElectrodes: false,
  earthElectrodeType: "Copper",
  earthElectrodeLocation: "Ground",
  electrodeResistanceToEarth: "1Ω",
  earthingConductorMaterial: "Copper",
  earthingConductorCSA: "25mm²",
  earthingConductorVerified: true,
  mainProtectiveBondingConductorMaterial: "Copper",
  mainProtectiveBondingConductorCSA: "16mm²",
  mainProtectiveBondingConductorVerified: true,
  waterInstallationPipes: "Metal",
  gasInstallationPipes: "Metal",
  structuralSteel: "Yes",
  oilInstallationPipes: "Plastic",
  lightningProtection: "None",
  other: "",
  mainSwitchImage: "/images/mainSwitch.jpg",
  mainSwitchLocation: "Main panel",
  mainSwitchBSNumber: "1234",
  mainSwitchType: "Mains",
  mainSwitchRating: "100A",
  mainSwitchPoles: "3",
  mainSwitchCurrentRating: "100A",
  mainSwitchVoltageRating: "230V",
  mainSwitchRCDOperatingCurrent: "30mA",
  mainSwitchRCDType: "Type A",
  mainSwitchRCDRatedTimeDelay: "300ms",
  mainSwitchRCDMeasuredOperatingTime: "150ms",

  observations: [
    {
      observationItemNumber: "1",
      observationDetails: "Check wiring integrity in living room",
      observationCode: "A001",
      observationLocation: "Living Room",
    },
    {
      observationItemNumber: "2",
      observationDetails: "Inspect condition of main switchboard",
      observationCode: "A002",
      observationLocation: "Main Switchboard",
    },
    {
      observationItemNumber: "3",
      observationDetails: "Verify earthing conductor continuity",
      observationCode: "A003",
      observationLocation: "Building Exterior",
    },
    {
      observationItemNumber: "4",
      observationDetails: "Test residual current devices",
      observationCode: "A004",
      observationLocation: "Kitchen",
    },
    {
      observationItemNumber: "5",
      observationDetails: "Assess fire alarm system connection",
      observationCode: "A005",
      observationLocation: "Hallway",
    },
  ],

  item_1_1A: "na" as const,
  item_1_1B: "na" as const,
  item_1_1C: "na" as const,
  item_1_1D: "na" as const,
  item_1_1E: "na" as const,
  item_1_1F: "na" as const,
  item_1_2: "na" as const,
  item_1_3: "na" as const,

  item_2_1: "na" as const,
  item_2_2: "na" as const,

  item_3_1A: "na" as const,
  item_3_1B: "na" as const,
  item_3_1C: "na" as const,
  item_3_1D: "na" as const,
  item_3_1E: "na" as const,
  item_3_1F: "na" as const,
  item_3_1G: "na" as const,
  item_3_1H: "na" as const,
  item_3_1I: "na" as const,
  item_3_2: "na" as const,
  item_3_3A: "na" as const,
  item_3_3B: "na" as const,
  item_3_3C: "na" as const,
  item_3_3D: "na" as const,
  item_3_3E: "na" as const,
  item_3_3F: "na" as const,

  item_4_1: "na" as const,
  item_4_2: "na" as const,
  item_4_3: "na" as const,
  item_4_4: "na" as const,
  item_4_5: "na" as const,
  item_4_6: "na" as const,
  item_4_7: "na" as const,
  item_4_8: "na" as const,
  item_4_9: "na" as const,
  item_4_10: "na" as const,
  item_4_11: "na" as const,
  item_4_12: "na" as const,
  item_4_13: "na" as const,
  item_4_14: "na" as const,
  item_4_15: "na" as const,
  item_4_16: "na" as const,
  item_4_17: "na" as const,
  item_4_18: "na" as const,
  item_4_19: "na" as const,
  item_4_20: "na" as const,
  item_4_21: "na" as const,
  item_4_22: "na" as const,
  item_4_23: "na" as const,
  item_4_24: "na" as const,
  item_4_25: "na" as const,

  item_5_1: "na" as const,
  item_5_2: "na" as const,
  item_5_3: "na" as const,
  item_5_4: "na" as const,
  item_5_5: "na" as const,
  item_5_6: "na" as const,
  item_5_7: "na" as const,
  item_5_8: "na" as const,
  item_5_9: "na" as const,
  item_5_10: "na" as const,
  item_5_11: "na" as const,
  item_5_12: "na" as const,
  item_5_13: "na" as const,
  item_5_14A: "na" as const,
  item_5_14B: "na" as const,
  item_5_15: "na" as const,
  item_5_16: "na" as const,
  item_5_17: "na" as const,
  item_5_18: "na" as const,
  item_5_19: "na" as const,
  item_5_20: "na" as const,
  item_5_21: "na" as const,
  item_5_22: "na" as const,
  item_5_23: "na" as const,
  item_5_24: "na" as const,

  item_6_1: "na" as const,
  item_6_2: "na" as const,
  item_6_3: "na" as const,
  item_6_4: "na" as const,
  item_6_5: "na" as const,
  item_6_6: "na" as const,
  item_6_7: "na" as const,
  item_6_8: "na" as const,
  item_6_9: "na" as const,
  item_6_10: "na" as const,
  item_6_11: "na" as const,
  item_6_12A: "na" as const,
  item_6_12B: "na" as const,
  item_6_13A: "na" as const,
  item_6_13B: "na" as const,
  item_6_13C: "na" as const,
  item_6_13D: "na" as const,
  item_6_13E: "na" as const,
  item_6_14: "na" as const,
  item_6_15: "na" as const,
  item_6_16: "na" as const,
  item_6_17A: "na" as const,
  item_6_17B: "na" as const,
  item_6_17C: "na" as const,
  item_6_17D: "na" as const,
  item_6_18: "na" as const,
  item_6_19: "na" as const,
  item_6_20: "na" as const,

  item_7_1A: "na" as const,
  item_7_1B: "na" as const,
  item_7_1C: "na" as const,
  item_7_1D: "na" as const,
  item_7_1E: "na" as const,
  item_7_1F: "na" as const,
  item_7_2A: "na" as const,
  item_7_2B: "na" as const,
  item_7_2C: "na" as const,
  item_7_2D: "na" as const,
  item_7_3A: "na" as const,
  item_7_3B: "na" as const,
  item_7_3C: "na" as const,
  item_7_3D: "na" as const,
  item_7_4A: "na" as const,
  item_7_4B: "na" as const,

  item_8_1: "na" as const,
  item_8_2: "na" as const,
  item_8_3: "na" as const,
  item_8_4: "na" as const,
  item_8_5: "na" as const,
  item_8_6: "na" as const,
  item_8_7A: "na" as const,
  item_8_7B: "na" as const,
  item_8_7C: "na" as const,
  item_8_7D: "na" as const,

  item_9_1A: "na" as const,
  item_9_1B: "na" as const,
  item_9_1C: "na" as const,
  item_9_1D: "na" as const,
  item_9_1E: "na" as const,
  item_9_1F: "na" as const,
  item_9_1G: "na" as const,
  item_9_1H: "na" as const,
  item_9_2: "na" as const,

  item_10_0: "na" as const,

  dbs: [
    {
      dbDesignation: "DB1",
      dbLocation: "Main Electrical Room",
      dbZdb: "0.35Ω",
      dbIpf: "5.2kA",
      dbConfirmationOfSupplyPolarity: true,
      dbPhaseSequenceConfirmed: true,
      dbSPDType: "Type 2",
      dbSPDStatusIndicator: true,
      dbSupplyFrom: "Main Supply",
      dbOCPDBSnumber: "BS 88",
      dbOCPDType: "Fuse",
      dbOCPDNominalVoltage: "230V",
      dbOCPDRating: "100A",
      dbOCPDNumberOfPhases: "Single",
      dbRCDBSNumber: "BS EN 61008",
      dbRCDType: "AC",
      dbRCDOperatingCurrent: "30mA",
      dbRCDNumberOfPoles: "2",
      dbRCDOperatingTime: "300ms",
      testedByName: "John Doe",
      testedByPosition: "Electrician",
      testedBySignature: "JohnDoeSignature",
      testedBySignatureDate: "",
      testInstrumentMultiFunctionSerialNumber: "MFS12345",
      testInstrumentContinuitySerialNumber: "CNS67890",
      testInstrumentInsulationResistanceSerialNumber: "IRS11223",
      testInstrumentEarthFaultLoopImpedanceSerialNumber: "ELI33445",
      testInstrumentEarthElectrodeSerialNumber: "EES55667",
      testInstrumentRCDSerialNumber: "RCD77889",
      dbCircuits: Array.from({ length: 5 }, (_, i) => ({
        circuitNumber: (i + 1).toString(),
        circuitDescription: `Circuit ${i + 1} Description`,
        circuitTypeOfWiring: "T&E",
        circuitReferenceMethod: "B",
        circuitNumberOfPoints: "4",
        circuitConductorLiveCSA: "2.5mm²",
        circuitConductorCPCCSA: "1.5mm²",
        circuitMaxDisconnectionTime: "0.4s",
        circuitOCPDBSNumber: "BS 60898",
        circuitOCPDType: "MCB",
        circuitOCPDRating: "32A",
        circuitOCPDShortCircuitCapacity: "6kA",
        circuitOCPDMaxPermittedZs: "1.37Ω",
        circuitRCDBSNumber: "BS EN 61008",
        circuitRCDType: "AC",
        circuitRCDRating: "30mA",
        circuitRCDOperatingCurrent: "30mA",
        circuitContinuityr1: "0.5Ω",
        circuitContinuityrn: "0.5Ω",
        circuitContinuityr2: "1.0Ω",
        circuitContinuityR1R2: "1.5Ω",
        circuitContinuityR2: "1.0Ω",
        circuitInsulationResistanceLiveLive: "200MΩ",
        circuitInsulationResistanceLiveEarth: "150MΩ",
        circuitInsulationResistanceTestVoltage: "500V",
        circuitPolarity: true,
        circuitMaximumZs: "1.37Ω",
        circuitRCDOperatingTime: "300ms",
        circuitRCDOTestButton: true,
        circuitAFDDOTestButton: true,
        circuitComments: `No issues on Circuit ${i + 1}`,
        circuitsEquipmentVunerableToDamage: "No",
      })),
    },
    {
      dbDesignation: "DB2",
      dbLocation: "Garage",
      dbZdb: "0.40Ω",
      dbIpf: "4.8kA",
      dbConfirmationOfSupplyPolarity: true,
      dbPhaseSequenceConfirmed: true,
      dbSPDType: "Type 2",
      dbSPDStatusIndicator: true,
      dbSupplyFrom: "Sub-main",
      dbOCPDBSnumber: "BS 1361",
      dbOCPDType: "Fuse",
      dbOCPDNominalVoltage: "230V",
      dbOCPDRating: "63A",
      dbOCPDNumberOfPhases: "Single",
      dbRCDBSNumber: "BS EN 61008",
      dbRCDType: "A",
      dbRCDOperatingCurrent: "30mA",
      dbRCDNumberOfPoles: "2",
      dbRCDOperatingTime: "300ms",
      testedByName: "John Doe",
      testedByPosition: "Electrician",
      testedBySignature: "JohnDoeSignature",
      testedBySignatureDate: "",
      testInstrumentMultiFunctionSerialNumber: "MFS12345",
      testInstrumentContinuitySerialNumber: "CNS67890",
      testInstrumentInsulationResistanceSerialNumber: "IRS11223",
      testInstrumentEarthFaultLoopImpedanceSerialNumber: "ELI33445",
      testInstrumentEarthElectrodeSerialNumber: "EES55667",
      testInstrumentRCDSerialNumber: "RCD77889",
      dbCircuits: Array.from({ length: 5 }, (_, i) => ({
        circuitNumber: (i + 1).toString(),
        circuitDescription: `Garage Circuit ${i + 1}`,
        circuitTypeOfWiring: "T&E",
        circuitReferenceMethod: "C",
        circuitNumberOfPoints: "3",
        circuitConductorLiveCSA: "2.5mm²",
        circuitConductorCPCCSA: "1.5mm²",
        circuitMaxDisconnectionTime: "0.4s",
        circuitOCPDBSNumber: "BS 60898",
        circuitOCPDType: "MCB",
        circuitOCPDRating: "20A",
        circuitOCPDShortCircuitCapacity: "6kA",
        circuitOCPDMaxPermittedZs: "2.0Ω",
        circuitRCDBSNumber: "BS EN 61008",
        circuitRCDType: "A",
        circuitRCDRating: "30mA",
        circuitRCDOperatingCurrent: "30mA",
        circuitContinuityr1: "0.6Ω",
        circuitContinuityrn: "0.6Ω",
        circuitContinuityr2: "1.2Ω",
        circuitContinuityR1R2: "1.8Ω",
        circuitContinuityR2: "1.2Ω",
        circuitInsulationResistanceLiveLive: "180MΩ",
        circuitInsulationResistanceLiveEarth: "140MΩ",
        circuitInsulationResistanceTestVoltage: "500V",
        circuitPolarity: true,
        circuitMaximumZs: "2.0Ω",
        circuitRCDOperatingTime: "300ms",
        circuitRCDOTestButton: true,
        circuitAFDDOTestButton: true,
        circuitComments: `No issues on Garage Circuit ${i + 1}`,
        circuitsEquipmentVunerableToDamage: "No",
      })),
    },
  ],
};
