export const DefaultValues = {
  contractorTradingName: "",
  contractorAddress: "",
  contractorPhone: "",
  contractorEmail: "",
  contractorGoverningBody: "",
  contractorGoverningBodyNumber: "",

  clientReferenceNumber: "",
  clientTradingName: "",
  clientAddress: "",
  clientPostcode: "",
  clientTelephone: "",

  propertyReferenceNumber: "",
  propertyOccupier: "",
  propertyAddress: "",
  propertyPostcode: "",
  propertyTelephone: "",

  purpose: "",
  startDate: "",
  endDate: "",
  recordsAvailable: false,
  previousReportAvailable: false,
  previousReportDate: "",

  descriptionOfPremises: "",
  estimatedAgeOfElectricalInstallation: "",
  evidenceOfAlterations: false,
  estimatedAgeOfAlterations: "",

  generalConditionOfTheInstallation: "",
  overallAssessmentOfTheInstallation: "",

  regulationAccordance: "",
  electricalInstalationCoveredByThisReport: "",
  agreedLimitations: "",
  agreedLimitationsWith: "",
  operationalLimitations: "",

  inspectorsName: "",
  inspectorsSignature: "",
  inspectorsSignatureDate: "",
  retestDate: "",
  reasonForRecommendation: "",
  qualifiedSupervisorsName: "",
  qualifiedSupervisorsSignature: "",
  qualifiedSupervisorsSignatureDate: "",

  observations: [
    {
      observationItemNumber: "",
      observationDetails: "",
      observationCode: "",
      observationLocation: "",
    },
  ],

  systemTypeAndEarthingArrangemets: "",
  supplyProtectiveDeviceBSNumber: "",
  supplyProtectiveDeviceType: "",
  supplyProtectiveDeviceRatedCurrent: "",
  numberAndTypeOfLiveConductors: "",
  confirmationOfSupplyPolarity: true,
  otherSourcesOfSupply: "",
  nominalVoltageBetweenLines: "",
  nominalLineVoltageToEarth: "",
  nominalFrequency: "",
  prospectiveFaultCurrent: "",
  externalEarthFaultLoopImpedance: "",

  maximumDemand: "",
  distributorsFacility: true,
  installationEarthElectrodes: false,
  earthElectrodeType: "",
  earthElectrodeLocation: "",
  electrodeResistanceToEarth: "",
  earthingConductorMaterial: "",
  earthingConductorCSA: "",
  earthingConductorVerified: false,
  mainProtectiveBondingConductorMaterial: "",
  mainProtectiveBondingConductorCSA: "",
  mainProtectiveBondingConductorVerified: false,
  waterInstallationPipes: "",
  gasInstallationPipes: "",
  structuralSteel: "",
  oilInstallationPipes: "",
  lightningProtection: "",
  other: "",
  mainSwitchImage: "",
  mainSwitchLocation: "",
  mainSwitchBSNumber: "",
  mainSwitchType: "",
  mainSwitchRating: "",
  mainSwitchPoles: "",
  mainSwitchCurrentRating: "",
  mainSwitchVoltageRating: "",
  mainSwitchRCDOperatingCurrent: "",
  mainSwitchRCDType: "",
  mainSwitchRCDRatedTimeDelay: "",
  mainSwitchRCDMeasuredOperatingTime: "",

  item_1_1A: "na" as const,
  item_1_1B: "na" as const,
  item_1_1C: "na" as const,
  item_1_1D: "na" as const,
  item_1_1E: "na" as const,
  item_1_1F: "na" as const,
  item_1_2: "na" as const,
  item_1_3: "na" as const,

  item_2_1: "na" as const,
  item_2_2: "na" as const,

  item_3_1A: "na" as const,
  item_3_1B: "na" as const,
  item_3_1C: "na" as const,
  item_3_1D: "na" as const,
  item_3_1E: "na" as const,
  item_3_1F: "na" as const,
  item_3_1G: "na" as const,
  item_3_1H: "na" as const,
  item_3_1I: "na" as const,
  item_3_2: "na" as const,
  item_3_3A: "na" as const,
  item_3_3B: "na" as const,
  item_3_3C: "na" as const,
  item_3_3D: "na" as const,
  item_3_3E: "na" as const,
  item_3_3F: "na" as const,

  item_4_1: "na" as const,
  item_4_2: "na" as const,
  item_4_3: "na" as const,
  item_4_4: "na" as const,
  item_4_5: "na" as const,
  item_4_6: "na" as const,
  item_4_7: "na" as const,
  item_4_8: "na" as const,
  item_4_9: "na" as const,
  item_4_10: "na" as const,
  item_4_11: "na" as const,
  item_4_12: "na" as const,
  item_4_13: "na" as const,
  item_4_14: "na" as const,
  item_4_15: "na" as const,
  item_4_16: "na" as const,
  item_4_17: "na" as const,
  item_4_18: "na" as const,
  item_4_19: "na" as const,
  item_4_20: "na" as const,
  item_4_21: "na" as const,
  item_4_22: "na" as const,
  item_4_23: "na" as const,
  item_4_24: "na" as const,
  item_4_25: "na" as const,

  item_5_1: "na" as const,
  item_5_2: "na" as const,
  item_5_3: "na" as const,
  item_5_4: "na" as const,
  item_5_5: "na" as const,
  item_5_6: "na" as const,
  item_5_7: "na" as const,
  item_5_8: "na" as const,
  item_5_9: "na" as const,
  item_5_10: "na" as const,
  item_5_11: "na" as const,
  item_5_12: "na" as const,
  item_5_13: "na" as const,
  item_5_14A: "na" as const,
  item_5_14B: "na" as const,
  item_5_15: "na" as const,
  item_5_16: "na" as const,
  item_5_17: "na" as const,
  item_5_18: "na" as const,
  item_5_19: "na" as const,
  item_5_20: "na" as const,
  item_5_21: "na" as const,
  item_5_22: "na" as const,
  item_5_23: "na" as const,
  item_5_24: "na" as const,

  item_6_1: "na" as const,
  item_6_2: "na" as const,
  item_6_3: "na" as const,
  item_6_4: "na" as const,
  item_6_5: "na" as const,
  item_6_6: "na" as const,
  item_6_7: "na" as const,
  item_6_8: "na" as const,
  item_6_9: "na" as const,
  item_6_10: "na" as const,
  item_6_11: "na" as const,
  item_6_12A: "na" as const,
  item_6_12B: "na" as const,
  item_6_13A: "na" as const,
  item_6_13B: "na" as const,
  item_6_13C: "na" as const,
  item_6_13D: "na" as const,
  item_6_13E: "na" as const,
  item_6_14: "na" as const,
  item_6_15: "na" as const,
  item_6_16: "na" as const,
  item_6_17A: "na" as const,
  item_6_17B: "na" as const,
  item_6_17C: "na" as const,
  item_6_17D: "na" as const,
  item_6_18: "na" as const,
  item_6_19: "na" as const,
  item_6_20: "na" as const,

  item_7_1A: "na" as const,
  item_7_1B: "na" as const,
  item_7_1C: "na" as const,
  item_7_1D: "na" as const,
  item_7_1E: "na" as const,
  item_7_1F: "na" as const,
  item_7_2A: "na" as const,
  item_7_2B: "na" as const,
  item_7_2C: "na" as const,
  item_7_2D: "na" as const,
  item_7_3A: "na" as const,
  item_7_3B: "na" as const,
  item_7_3C: "na" as const,
  item_7_3D: "na" as const,
  item_7_4A: "na" as const,
  item_7_4B: "na" as const,

  item_8_1: "na" as const,
  item_8_2: "na" as const,
  item_8_3: "na" as const,
  item_8_4: "na" as const,
  item_8_5: "na" as const,
  item_8_6: "na" as const,
  item_8_7A: "na" as const,
  item_8_7B: "na" as const,
  item_8_7C: "na" as const,
  item_8_7D: "na" as const,

  item_9_1A: "na" as const,
  item_9_1B: "na" as const,
  item_9_1C: "na" as const,
  item_9_1D: "na" as const,
  item_9_1E: "na" as const,
  item_9_1F: "na" as const,
  item_9_1G: "na" as const,
  item_9_1H: "na" as const,
  item_9_2: "na" as const,

  item_10_0: "na" as const,

  db: [],
};
