import { z } from "zod";

export const UpdateDistributionEquipmentSchema = z.object({
  id: z.string().cuid(),
  item_4_1: z.string().optional(),
  item_4_2: z.string().optional(),
  item_4_3: z.string().optional(),
  item_4_4: z.string().optional(),
  item_4_5: z.string().optional(),
  item_4_6: z.string().optional(),
  item_4_7: z.string().optional(),
  item_4_8: z.string().optional(),
  item_4_9: z.string().optional(),
  item_4_10: z.string().optional(),
  item_4_11: z.string().optional(),
  item_4_12: z.string().optional(),
  item_4_13: z.string().optional(),
  item_4_14: z.string().optional(),
  item_4_15: z.string().optional(),
  item_4_16: z.string().optional(),
  item_4_17: z.string().optional(),
  item_4_18: z.string().optional(),
  item_4_19: z.string().optional(),
  item_4_20: z.string().optional(),
  item_4_21: z.string().optional(),
  item_4_22: z.string().optional(),
  item_4_23: z.string().optional(),
  item_4_24: z.string().optional(),
  item_4_25: z.string().optional(),
});
