import { z } from "zod";

export const Schema = z.object({
  item_4_1: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_2: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_3: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_4: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_5: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_6: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_7: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_8: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_9: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_10: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_11: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_12: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_13: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_14: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_15: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_16: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_17: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_18: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_19: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_20: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_21: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_22: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_23: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_24: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_4_25: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
});
