export const inspectionItems = [
  { id: "item_3_1A", item: "3.1A", label: "Main earthing / bonding arrangement (411.3; Chap. 54)" },
  { id: "item_3_1B", item: "3.1B", label: "Presence of distributor\u2019s earthing arrangement (542.1.2.1; 542.1.2.2), or presence of installation earth electrode arrangement (542.1.2.3)" },
  { id: "item_3_1C", item: "3.1C", label: "Adequacy of earthing conductor size (542.3; 543.1.1)" },
  { id: "item_3_1D", item: "3.1D", label: "Adequacy of earthing conductor connections (542.3.2)" },
  { id: "item_3_1E", item: "3.1E", label: "Accessibility of earthing conductor connections (543.3.2)" },
  { id: "item_3_1F", item: "3.1F", label: "Adequacy of main protective bonding conductor sizes (544.1.1)" },
  { id: "item_3_1G", item: "3.1G", label: "Adequacy and location of main protective bonding conductor connections (544.1.2)" },
  { id: "item_3_1H", item: "3.1H", label: "Accessibility of all protective bonding connections (543.3.2)" },
  { id: "item_3_1I", item: "3.1I", label: "Provision of earthing / bonding labels at all appropriate locations (514.13.1)" },
  { id: "item_3_2", item: "3.2", label: "FELV - requirements satisfied (411.7)" },
  { id: "item_3_3A", item: "3.3A", label: "Non-conducting location (418.1)" },
  { id: "item_3_3B", item: "3.3B", label: "Earth-free local equipotential bonding (418.2)" },
  { id: "item_3_3C", item: "3.3C", label: "Electrical separation (413; 418.3)" },
  { id: "item_3_3D", item: "3.3D", label: "Double insulation (412)" },
  { id: "item_3_3E", item: "3.3E", label: "Reinforced insulation (412)" },
  { id: "item_3_3F", item: "3.3F", label: "Provisions where automatic disconnection of supply is not feasible (419)" },
];
