export const inspectionItems = [
  { id: "item_1_1A", item: "1.1A", label: "Service cable" },
  { id: "item_1_1B", item: "1.1B", label: "Service head" },
  { id: "item_1_1C", item: "1.1C", label: "Earthing arrangement" },
  { id: "item_1_1D", item: "1.1D", label: "Meter tails" },
  { id: "item_1_1E", item: "1.1E", label: "Metering equipment" },
  { id: "item_1_1F", item: "1.1F", label: "Isolator, where present" },
  { id: "item_1_2", item: "1.2", label: "Consumer\u2019s isolator, where present" },
  { id: "item_1_3", item: "1.3", label: "Consumer\u2019s meter tails" },

  { id: "item_2_1", item: "2.1", label: "Adequate arrangements where a generating set operates as a switched alternative to the public supply (551.6)" },
  { id: "item_2_2", item: "2.2", label: "Adequate arrangements where a generating set operates in parallel with the public supply (551.7)" },

  { id: "item_3_1A", item: "3.1A", label: "Main earthing / bonding arrangement (411.3; Chap. 54)" },
  { id: "item_3_1B", item: "3.1B", label: "Presence of distributor\u2019s earthing arrangement (542.1.2.1; 542.1.2.2), or presence of installation earth electrode arrangement (542.1.2.3)" },
  { id: "item_3_1C", item: "3.1C", label: "Adequacy of earthing conductor size (542.3; 543.1.1)" },
  { id: "item_3_1D", item: "3.1D", label: "Adequacy of earthing conductor connections (542.3.2)" },
  { id: "item_3_1E", item: "3.1E", label: "Accessibility of earthing conductor connections (543.3.2)" },
  { id: "item_3_1F", item: "3.1F", label: "Adequacy of main protective bonding conductor sizes (544.1.1)" },
  { id: "item_3_1G", item: "3.1G", label: "Adequacy and location of main protective bonding conductor connections (544.1.2)" },
  { id: "item_3_1H", item: "3.1H", label: "Accessibility of all protective bonding connections (543.3.2)" },
  { id: "item_3_1I", item: "3.1I", label: "Provision of earthing / bonding labels at all appropriate locations (514.13.1)" },
  { id: "item_3_2", item: "3.2", label: "FELV - requirements satisfied (411.7)" },
  { id: "item_3_3A", item: "3.3A", label: "Non-conducting location (418.1)" },
  { id: "item_3_3B", item: "3.3B", label: "Earth-free local equipotential bonding (418.2)" },
  { id: "item_3_3C", item: "3.3C", label: "Electrical separation (413; 418.3)" },
  { id: "item_3_3D", item: "3.3D", label: "Double insulation (412)" },
  { id: "item_3_3E", item: "3.3E", label: "Reinforced insulation (412)" },
  { id: "item_3_3F", item: "3.3F", label: "Provisions where automatic disconnection of supply is not feasible (419)" },

  { id: "item_4_1", item: "4.1", label: "Adequacy of working space / accessibility to equipment (132.12; 513.1)" },
  { id: "item_4_2", item: "4.2", label: "Security of fixing (134.1.1)" },
  { id: "item_4_3", item: "4.3", label: "Condition of insulation of live parts (416.1)" },
  { id: "item_4_4", item: "4.4", label: "Adequacy security of barriers or enclosures (416.2.3)" },
  { id: "item_4_5", item: "4.5", label: "Condition of enclosure(s) in terms of IP rating, etc. (416.2)" },
  { id: "item_4_6", item: "4.6", label: "Condition of enclosure(s) in terms of fire rating, etc. (421.1.201; 421.1.6; 526.5)" },
  { id: "item_4_7", item: "4.7", label: "Enclosure not damaged / deteriorated so as to impair safety (651.2)" },
  { id: "item_4_8", item: "4.8", label: "Presence and effectiveness of obstacles (417.2)" },
  { id: "item_4_9", item: "4.9", label: "Presence of main switch(es), linked where required (462.1; 462.1.201; 462.2)" },
  { id: "item_4_10", item: "4.10", label: "Operation of main switch(es) (functional check) (643.10)" },
  { id: "item_4_11", item: "4.11", label: "Manual operation of circuit-breakers, RCDs and AFDDs to prove functionality (643.10)" },
  { id: "item_4_12", item: "4.12", label: "Confirmation that integral test button / switch causes RCD(s) to trip when operated (functional check) (643.10)" },
  { id: "item_4_13", item: "4.13", label: "RCD(s) provided for fault protection - includes RCBOs (411.4.204; 411.4.5; 411.5.2; 531.2)" },
  { id: "item_4_14", item: "4.14", label: "RCD(s) provided for additional protection / requirements, where required - includes RCBOs (411.3.3; 415.1)" },
  { id: "item_4_15", item: "4.15", label: "Presence of RCD six-monthly test notice, where required (514.12.2)" },
  { id: "item_4_16", item: "4.16", label: "Confirmation that integral test button / switch, where present, causes AFDD to trip when operated (643.10)" },
  { id: "item_4_17", item: "4.17", label: "Presence of diagrams, charts or schedules at or near equipment, where required (514.9.1)" },
  { id: "item_4_18", item: "4.18", label: "Presence of alternative supply warning notice at or near equipment, where required (514.15)" },
  { id: "item_4_19", item: "4.19", label: "Presence of next inspection recommendation label, where required (514.12.1)" },
  { id: "item_4_20", item: "4.20", label: "Presence of other required labelling (please specify) (514)" },
  { id: "item_4_22", item: "4.22", label: "Single-pole switching or protective devices in line conductors only (132.14.1; 530.3.3)" },
  { id: "item_4_23", item: "4.23", label: "Protection against mechanical damage where cables enter equipment (522.8.1; 522.8.5; 522.8.11)" },
  { id: "item_4_24", item: "4.24", label: "Protection against electromagnetic effects where cables enter ferromagnetic enclosures (521.5.1)" },
  { id: "item_4_25", item: "4.25", label: "Confirmation that ALL conductor connections, including connections to busbars, are correctly located in terminals and are tight and secure (526.1)" },

  { id: "item_5_1", item: "5.1", label: "Identification of conductors (514.3)" },
  { id: "item_5_2", item: "5.2", label: "Cables correctly supported throughout their run (521.10.202; 522.8.5)" },
  { id: "item_5_3", item: "5.3", label: "Condition of insulation of live parts (416.1)" },
  { id: "item_5_4", item: "5.4", label: "Non-sheathed cables protected by enclosure in conduit, ducting or trunking (521.10.1)" },
  { id: "item_5_5", item: "5.5", label: "Suitability of containment systems for continued use (including flexible conduit) (522)" },
  { id: "item_5_6", item: "5.6", label: "Cables correctly terminated in enclosures (526)" },
  { id: "item_5_7", item: "5.7", label: "Examination of cables for signs of unacceptable thermal or mechanical damage / deterioration (421.1; 522.6)" },
  { id: "item_5_8", item: "5.8", label: "Adequacy of cables for current-carrying capacity with regard for the type and nature of installation (523)" },
  { id: "item_5_9", item: "5.9", label: "Adequacy of protective devices; type and rated current for fault protection (411.3)" },
  { id: "item_5_10", item: "5.10", label: "Presence and adequacy of circuit protective conductors (411.3.1.1; 543.1)" },
  { id: "item_5_11", item: "5.11", label: "Coordination between conductors and overload protective devices (433.1; 533.2.1)" },
  { id: "item_5_12", item: "5.12", label: "Cable installation methods / practices with regard to the type and nature of installation and external influences (522)" },
  { id: "item_5_13", item: "5.13", label: "Where exposed to direct sunlight, cable of a suitable type (522.11.1)" },
  { id: "item_5_14A", item: "5.14A", label: "Installed in prescribed zones (see Section D. Extent and limitations) (522.6.202)" },
  { id: "item_5_15", item: "5.15", label: "Provision of fire barriers, sealing arrangements and protection against thermal effects (527)" },
  { id: "item_5_16", item: "5.16", label: "Band II cables segregated / separated from Band I cables (528.1)" },
  { id: "item_5_17", item: "5.17", label: "Cables segregated / separated from non-electrical services (528.3)" },
  { id: "item_5_18", item: "5.18", label: "Condition of circuit accessories (651.2)" },
  { id: "item_5_19", item: "5.19", label: "Suitability of circuit accessories for external influences (512.2)" },
  { id: "item_5_20", item: "5.20", label: "Single-pole switching or protective devices in line conductors only (132.14.1; 530.3.3)" },
  { id: "item_5_22", item: "5.22", label: "Presence, operation and correct location of appropriate devices for isolation and switching (Chap. 46; 537)" },
  { id: "item_5_23", item: "5.23", label: "General condition of wiring system (651.2)" },
  { id: "item_5_24", item: "5.24", label: "Temperature rating of cable insulation (522.1.1; Table 52.1)" },

  { id: "item_6_1", item: "6.1", label: "Identification of conductors (514.3)" },
  { id: "item_6_2", item: "6.2", label: "Cables correctly supported throughout their run (521.10.202; 522.8.5)" },
  { id: "item_6_3", item: "6.3", label: "Condition of insulation of live parts (416.1)" },
  { id: "item_6_4", item: "6.4", label: "Non-sheathed cables protected by enclosure in conduit, ducting or trunking (521.10.1)" },
  { id: "item_6_5", item: "6.5", label: "Suitability of containment systems for continued use (including flexible conduit) (522)" },
  { id: "item_6_6", item: "6.6", label: "Adequacy of cables for current-carrying capacity with regard for the type and nature of installation (523)" },
  { id: "item_6_7", item: "6.7", label: "Adequacy of protective devices; type and rated current for fault protection (411.3)" },
  { id: "item_6_8", item: "6.8", label: "Presence and adequacy of circuit protective conductors (411.3.1.1; 543.1)" },
  { id: "item_6_9", item: "6.9", label: "Coordination between conductors and overload protective devices (433.1; 533.2.1)" },
  { id: "item_6_10", item: "6.10", label: "Wiring system(s) appropriate for the type and nature of the installation and external influences (522)" },
  { id: "item_6_11", item: "6.11", label: "Where exposed to direct sunlight, cable of a suitable type (522.11.1)" },
  { id: "item_6_12A", item: "6.12A", label: "Installed in prescribed zones (see Section D. Extent and limitations) (522.6.202)" },
  { id: "item_6_13A", item: "6.13A", label: "*For all socket-outlets of rating 32 A or less (411.3.3)" },
  { id: "item_6_13B", item: "6.13B", label: "*For the supply of mobile equipment not exceeding 32 A rating for use outdoors (411.3.3)" },
  { id: "item_6_13C", item: "6.13C", label: "*For cables concealed in walls at a depth of less than 50 mm (522.6.202)" },
  { id: "item_6_13D", item: "6.13D", label: "*For cables concealed in walls / partitions containing metal parts regardless of depth (522.6.203)" },
  { id: "item_6_13E", item: "6.13E", label: "*For final circuits supplying luminaires within domestic (household) premises (411.3.4)" },
  { id: "item_6_14", item: "6.14", label: "Provision of fire barriers, sealing arrangements and protection against thermal effects (527)" },
  { id: "item_6_15", item: "6.15", label: "Band II cables segregated / separated from Band I cables (528.1)" },
  { id: "item_6_16", item: "6.16", label: "Cables segregated / separated from non-electrical services (528.3)" },
  { id: "item_6_17A", item: "6.17A", label: "Connection under no undue strain (526.6)" },
  { id: "item_6_17B", item: "6.17B", label: "No basic insulation of a conductor visible outside enclosure (526.8)" },
  { id: "item_6_17C", item: "6.17C", label: "Connections of live conductors adequately enclosed (526.5)" },
  { id: "item_6_17D", item: "6.17D", label: "Adequately connected at point of entry to enclosure (glands, bushes, etc.) (522.8.5)" },
  { id: "item_6_18", item: "6.18", label: "Condition of accessories including socket-outlets, switches and joint boxes (651.2)" },
  { id: "item_6_19", item: "6.19", label: "Suitability of accessories for external influences (512.2)" },
  { id: "item_6_20", item: "6.20", label: "Single-pole switching or protective devices in line conductors only (132.14.1; 530.3.3)" },

  { id: "item_7_1A", item: "7.1A", label: "Presence and condition of appropriate devices (462; 537.2)" },
  { id: "item_7_1B", item: "7.1B", label: "Acceptable location - state if local or remote from equipment in question (462; 537.2.7)" },
  { id: "item_7_1C", item: "7.1C", label: "Capable of being secured in the OFF position (462.3)" },
  { id: "item_7_1D", item: "7.1D", label: "Correct operation verified (643.10)" },
  { id: "item_7_1E", item: "7.1E", label: "Clearly identified by position and / or durable marking (537.2.7)" },
  { id: "item_7_1F", item: "7.1F", label: "Warning label posted in situations where live parts cannot be isolated by the operation of a single device (514.11.1; 537.1.2)" },
  { id: "item_7_2A", item: "7.2A", label: "Presence and condition of appropriate devices (464.1; 537.3.2)" },
  { id: "item_7_2B", item: "7.2B", label: "Capable of being secured in the OFF position where not under continuous supervision (464.2)" },
  { id: "item_7_2C", item: "7.2C", label: "Correct operation verified (643.10)" },
  { id: "item_7_2D", item: "7.2D", label: "Clearly identified by position and / or durable marking (537.3.2.4)" },
  { id: "item_7_3A", item: "7.3A", label: "Presence and condition of appropriate devices (465; 537.3.3; 537.4)" },
  { id: "item_7_3B", item: "7.3B", label: "Readily accessible for operation where danger might occur (537.3.3.6)" },
  { id: "item_7_3C", item: "7.3C", label: "Correct operation verified (643.10)" },
  { id: "item_7_3D", item: "7.3D", label: "Clearly identified by position and / or durable marking (537.3.3.5; 537.3.3.6; 537.4.3; 537.4.4)" },
  { id: "item_7_4A", item: "7.4A", label: "Presence and condition of appropriate devices (537.3.1.1; 537.3.1.2)" },
  { id: "item_7_4B", item: "7.4B", label: "Correct operation verified (643.10)" },

  { id: "item_8_1", item: "8.1", label: "Condition of equipment in terms of IP rating, etc. (416.2; 422.3; 422.4; 522.4)" },
  { id: "item_8_2", item: "8.2", label: "Equipment does not constitute a fire hazard (421)" },
  { id: "item_8_3", item: "8.3", label: "Enclosure not damaged / deteriorated so as to impair safety (134.1.1; 416.2)" },
  { id: "item_8_4", item: "8.4", label: "Suitability for the environment and external influences (512.2)" },
  { id: "item_8_5", item: "8.5", label: "Security of fixing (134.1.1)" },
  { id: "item_8_7A", item: "8.7A", label: "Correct type of lamps fitted (559.3.1)" },
  { id: "item_8_7B", item: "8.7B", label: "Installed to minimise build-up of heat by use of \u201cfire rated\u201d fittings, insulation displacement box or similar (421.1.2)" },
  { id: "item_8_7C", item: "8.7C", label: "No signs of overheating to surrounding building fabric (559.4.1)" },
  { id: "item_8_7D", item: "8.7D", label: "No signs of overheating to conductors / terminations (526.1)" },

  { id: "item_9_1B", item: "9.1B", label: "Where used as a protective measure, requirements for SELV or PELV met (701.414.4.5)" },
  { id: "item_9_1C", item: "9.1C", label: "Shaver supply units complying with BS EN 61558-2-5 formerly BS 3535 (701.512.3)" },
  { id: "item_9_1D", item: "9.1D", label: "Presence of supplementary bonding conductors, unless not required by BS 7671: 2018 (701.415.2)" },
  { id: "item_9_1E", item: "9.1E", label: "Low voltage (e.g. 230 volt) socket-outlets sited at least 2.5 m from zone 1 (701.512.3)" },
  { id: "item_9_1F", item: "9.1F", label: "Suitability of equipment for external influences for installed location in terms of IP rating (701.512.2)" },
  { id: "item_9_1G", item: "9.1G", label: "Suitability of accessories and controlgear etc. for a particular zone (701.512.3)" },
  { id: "item_9_1H", item: "9.1H", label: "Suitability of current-using equipment for particular position within the location (701.55)" },
  { id: "item_9_2", item: "9.2", label: "Other special installations or locations" },

  { id: "item_10_0", item: "10.0", label: "Prosumer\u2019s low voltage installation" },
];
