import { z } from "zod";

export const Schema = z.object({
  item_6_1: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_2: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_3: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_4: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_5: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_6: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_7: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_8: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_9: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_10: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_11: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_12A: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_12B: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_13A: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_13B: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_13C: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_13D: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_13E: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_14: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_15: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_16: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_17A: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_17B: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_17C: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_17D: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_18: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_19: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
  item_6_20: z.enum(["c1", "c2", "c3", "na", "lim", "r"] as const),
});
